### ISSUE TITLE
Future Support

### ISSUE THREAD

**Issue by kaumudpa** [devopsdao/webthree#1]
Hi! Are you planning to maintain this forked plugin for a long time?

Shall one replace webedart with your fork?

**Comment by makinghappen** [comment]
@kaumudpa yes, we are planning to support webthree in long-term, it can be used as drop-in replacement for web3dart.

**Comment by redDwarf03** [comment]
A new version is available on https://pub.dev/packages/webthree
@makinghappen, i think we can close this issue
