### ISSUE TITLE
How to manage revert

### ISSUE THREAD

**Issue by redDwarf03** [devopsdao/webthree#4]
I would like to catch revert keywords in smart contract
Is it possible with this lib ?
thx

**Comment by makinghappen** [comment]
@redDwarf03 it is not supported, I would like to have it as well, so future plans would include this, if you would also like to make a contribution- it is very welcome!

**Comment by redDwarf03** [comment]
PR https://github.com/devopsdao/webthree/pull/11

**Comment by redDwarf03** [comment]
Done on v2.5.9
https://pub.dev/packages/webthree
